name: Build 

on: [push]

jobs:
  answer-badge:
    name: Create Answer Badge
    runs-on: ubuntu-latest
    steps:
      - name: Get the Numbers
        run: echo "ANSWER=42" >> $GITHUB_ENV
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@main
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 2ab8f1d386f13aaebccbd87dac94068d
          filename: answer.json
          label: The Answer is
          message: ${{ env.ANSWER }}
          color: green
